gravitino.auxService.names=iceberg-rest
gravitino.iceberg-rest.classpath=iceberg-rest-server/libs, iceberg-rest-server/conf

# Iceberg REST service host and port
gravitino.iceberg-rest.host = 0.0.0.0
gravitino.iceberg-rest.httpPort = 9001

# Using JDBC backend for the REST Catalog
gravitino.iceberg-rest.catalog-backend=jdbc
gravitino.iceberg-rest.uri=jdbc:postgresql://postgres:5432/catalog_metastore_db
gravitino.iceberg-rest.warehouse=s3a://iceberg/warehouse
gravitino.iceberg-rest.catalog-backend-name=jdbc
gravitino.iceberg-rest.jdbc-user=postgres
gravitino.iceberg-rest.jdbc-password=postgres
gravitino.iceberg-rest.jdbc-initialize=true
gravitino.iceberg-rest.jdbc-driver=org.postgresql.Driver

# Using Minio as the object storage
gravitino.iceberg-rest.s3-endpoint=http://minio:9000
gravitino.iceberg-rest.s3-region=ap-southeast-3
gravitino.iceberg-rest.s3-path-style-access=true